before_install:
  - sudo apt-get install xsltproc
  - rm buddycloud.html
  - rm buddycloud.xml
script:
  - make
after_success: 
  - git config user.email "deploy@travis-ci.org"
  - git config user.name "Travis deploy"
  - cp buddycloud.html ~/
  - cp buddycloud.xml ~/
  - git checkout gh-pages
  - cp ~/buddycloud.html .
  - cp ~/buddycloud.xml .
  - git add -f buddycloud.xml
  - git add -f buddycloud.html
  - echo "Added generated files"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}@github.com" > .git/credentials
  - git remote add github "https://${GH_TOKEN}@github.com/buddycloud/buddycloud-xep.git" > /dev/null
  - git commit -a -m "Updating XEP"
  - git push github gh-pages
env:
  global:
  - secure: 'EF0sdrfSkfTIjaQwlFyC+Ma9IOwlKh1N7qKDS0RMo7goq+5cFXOMXvlYguuxPX6YnxBFRWhTz5NNMjeCfjchET0Mu5mvD9aS4g38yAYHsqD0pBxgjXx01rkVo45dtrwASHUWhbupAde7ppbYKbjY5spOvFvyI57Vo/9hcrazyVk='

