before_install:
  - sudo apt-get install xsltproc
  - rm -f index.html
  - rm -f buddycloud.xml
script:
  - make
after_success:
  - if [ "master" != $TRAVIS_BRANCH ]; then exit 0; fi; 
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis deploy"
  - cp index.html ~/
  - git remote add github "https://${GH_TOKEN}@github.com/buddycloud/buddycloud-xep.git" > /dev/null
  - git fetch github
  - git checkout gh-pages
  - cp ~/index.html .
  - git add -f index.html buddycloud.xml
  - echo "Added generated files"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}@github.com" > .git/credentials
  - git commit -a -m "Updating XEP"
  - git push github gh-pages > /dev/null
env:
  global:
  - secure: 'EF0sdrfSkfTIjaQwlFyC+Ma9IOwlKh1N7qKDS0RMo7goq+5cFXOMXvlYguuxPX6YnxBFRWhTz5NNMjeCfjchET0Mu5mvD9aS4g38yAYHsqD0pBxgjXx01rkVo45dtrwASHUWhbupAde7ppbYKbjY5spOvFvyI57Vo/9hcrazyVk='
